version: '3.8'

services:
  ros2-dev:
    build: .
    image: rs1_ros2_humble:latest
    container_name: ros2-rs1-dev
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=:0
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
      - PULSE_SERVER=$PULSE_SERVER
      # GPU support
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
    volumes:
      - .:/root/rs1_ws
      - ./docker-home:/root              # Mount entire repo as workspace 
      # WSL2 display support
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /mnt/wslg:/mnt/wslg:rw
      - /usr/lib/wsl:/usr/lib/wsl:ro
    networks:
      - ros2-network
    restart: unless-stopped
    # Enable GPU runtime
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: tail -f /dev/null

networks:
  ros2-network:
    driver: bridge
